spring:
  profiles.active: jpa, couchbase
---
spring:
  profiles: jpa
  jpa:
    generate-ddl: false
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
datasource:
  type: tomcat-jdbc
  url: jdbc:mysql://localhost/beer_demo?useSSL=false
  username: root
  password: beer
  driver-class-name: com.mysql.jdbc.Driver
---